target 'Universal' do
# U-Share SDK UI模块（分享面板，建议添加）
pod 'UMengUShare/UI'

# 集成微信(精简版0.2M)
pod 'UMengUShare/Social/ReducedWeChat'

# 集成QQ/QZone/TIM(精简版0.5M)
pod 'UMengUShare/Social/ReducedQQ'

# 集成新浪微博(完整版25.3M)
pod 'UMengUShare/Social/Sina'
end
