//
//  FMNIIListTVC.m
//  Universal
//
//  Created by Mac on 2018/2/13.
//  Copyright © 2018年 Sherdle. All rights reserved.
//

#import "FMNIIListTVC.h"
#import "WordpressViewController.h"
#import "FrontNavigationController.h"

@interface FMNIIListTVC ()<UIGestureRecognizerDelegate>
@property (nonatomic,strong) NSArray *shoesList;//品牌名称
@property (nonatomic,strong) NSArray *shoesURLList;//品牌URL
@property (nonatomic,strong) NSArray *clueList;//右侧索引


@end

@implementation FMNIIListTVC

- (void)viewDidLoad {
    [super viewDidLoad];
    self.title = @"品牌";
    self.navigationController.interactivePopGestureRecognizer.delegate = self;
}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

#pragma  lazy loading

- (NSArray*)shoesList{
    if (!_shoesList) {
        // _shoesList = @[@"品牌1",@"品牌2",@"品牌3",@"品牌4",@"品牌5",@"品牌6"];

_shoesList = @[
@"A. Testoni",
@"Acorn",
@"ADA Collection",
@"Adelyn Rae",
@"Aden + Anais",
@"Adidas",
@"Adrianna Papell",
@"Aerosoles",
@"Aetrex",
@"AG Adriano Goldschmied",
@"Agave Denim",
@"Agent Provocateur",
@"Agua De Coco By Liana Thomaz",
@"Ahnu",
@"Aidan Mattox",
@"AIGLE",
@"AKID Brand",
@"Akomplice",
@"Alberta Ferretti",
@"ALDO",
@"Alegria",
@"Alex And Ani",
@"Alexander McQueen",
@"Alexis Bittar",
@"Alice + Olivia",
@"Allen Allen",
@"Allen-Edmonds",
@"ALO",
@"Alpha Industries",
@"Alternative",
@"Altra Footwear",
@"AmeriBag, Inc.",
@"American Fighter",
@"American West",
@"Amiana",
@"Amuse Society",
@"AND1",
@"Andre Assous",
@"Anita",
@"Anne Klein New York",
@"Anne Klein",
@"Anuschka Handbags",
@"Appaman Kids",
@"Aquatalia",
@"Ara",
@"Aravon",
@"Arc'teryx",
@"Arche",
@"Arcopedico",
@"Ariat",
@"Armani Junior",
@"ASH",
@"ASICS",
@"ASKA",
@"Asolo",
@"ASTR The Label",
@"Athena Alexander",
@"Athena",
@"Athletic Propulsion Labs (APL)",
@"Atlas",
@"ATM Anthony Thomas Melillo",
@"Aventura Clothing",
@"B Brian Atwood",
@"B Collection By Bobeau",
@"B.Tempt'd",
@"Babiators",
@"Baby Deer",
@"Baby Jogger",
@"BabyBjorn",
@"Bacco Bucci",
@"Badgley Mischka",
@"Baffin",
@"Baggallini",
@"Bailey Of Hollywood",
@"Balenciaga",
@"Bally",
@"Bandolino",
@"Base London",
@"Bates Footwear",
@"BB Dakota",
@"BCBGeneration",
@"BCBGMAXAZRIA",
@"Bebe Au Lait",
@"BECCA By Rebecca Virtue",
@"Bed Stu",
@"BedHead",
@"Bedroom Athletics",
@"Bella-Vita",
@"BELSTAFF",
@"Ben Sherman",
@"Bernardo",
@"Bernie Mev.",
@"Betmar",
@"Betsey Johnson",
@"Beyond Yoga",
@"Big Agnes",
@"Billabong",
@"Billy Reid",
@"Bindya",
@"Bionica",
@"Birkenstock",
@"Bishop + Young",
@"Black Diamond",
@"Blanc Noir",
@"Blank NYC",
@"Bleu Rod Beattie",
@"Bloch",
@"Blondo",
@"Blowfish",
@"Blue Life",
@"Blundstone",
@"Bobux Kids",
@"Body Glove",
@"Bogner Fire + Ice",
@"Bogs",
@"BOOTIGHTS",
@"Born",
@"Bosca",
@"BOSS Hugo Boss",
@"Bostonian",
@"Botkier",
@"Boutique Moschino",
@"Bowie X James",
@"Brahmin",
@"Bric's Milano",
@"Briggs & Riley",
@"Brighton",
@"Brigitte Bailey",
@"Brixton",
@"Brooks",
@"Bruno Magli",
@"Buffalo David Bitton",
@"BUGATCHI",
@"BULA",
@"Bulova",
@"Burberry",
@"Burton",
@"C & C California",
@"Call It SPRING",
@"Callaway",
@"Calou Stockholm",
@"Calvin Klein",
@"CamelBak",
@"Camper",
@"Caparros",
@"Capezio",
@"Captain Fin",
@"Carhartt",
@"CARLOS By Carlos Santana",
@"Carole Hochman",
@"Carolina",
@"Carrera",
@"Carrucci",
@"Carve Designs",
@"Cashmere In Love",
@"Caterpillar",
@"CATHERINE Catherine Malandrino",
@"CeCe",
@"Celtek",
@"Chaco",
@"Champion",
@"Chan Luu",
@"Charles By Charles David",
@"Charlotte Olympia",
@"Chaser Kids",
@"Chicago Skates",
@"Chinese Laundry",
@"Chippewa",
@"CHLOE GOSSELIN",
@"Chloe",
@"Chooka",
@"CHOOZE",
@"Christin Michaels",
@"Chrome",
@"Cienta Kids Shoes",
@"Cinch",
@"Circa",
@"Citizen Watches",
@"Clarks",
@"Clayton",
@"Clear Weather",
@"COACH",
@"Coal",
@"Cobian",
@"Cole Haan",
@"Columbia",
@"Comfortiva",
@"Commando",
@"Converse",
@"Coobie",
@"Coolway",
@"Cordani",
@"Corral Boots",
@"Corso Como",
@"Cosabella",
@"Cosatto",
@"Costa",
@"COWBOYSBELT",
@"Crabbyclaws",
@"Creative Recreation",
@"Crocs",
@"Crosby Square",
@"Cruel",
@"Cufflinks Inc.",
@"Culture Phit",
@"Custom Ketchup",
@"CW-X",
@"Cycleur De Luxe",
@"Cote & Ciel",
@"D",
@"D.GNAK",
@"Dakine",
@"Dale Of Norway",
@"Dan Post",
@"Daniel Green",
@"Danner",
@"DANNIJO",
@"Dansko",
@"David Tate",
@"DBYD",
@"DC",
@"Dee Berkley",
@"Deer Stags",
@"Del Toro",
@"Delsey",
@"Depressed Monsters",
@"Deuter",
@"Dexter",
@"Diadora",
@"Diane Von Furstenberg",
@"Diesel",
@"Dingo",
@"DKNY",
@"DL1961",
@"Dockers",
@"Dogeared",
@"Dolce & Gabbana",
@"Dolce Vita",
@"Donald J Pliner",
@"Donna Morgan",
@"Dooney & Bourke",
@"Double D Ranchwear",
@"Doucal's",
@"Dr. Martens",
@"Dr. Scholl's",
@"Dragon Alliance",
@"Drew",
@"Drymax Sport",
@"DSQUARED2",
@"Dunham",
@"Durango",
@"DUVETICA",
@"Dylan By True Grit",
@"Eagle Creek",
@"Earth",
@"Eastland 1955",
@"Easy Spirit",
@"ECCO",
@"Echo",
@"Ecoths",
@"ED Ellen DeGeneres",
@"Eileen Fisher",
@"Eileen West",
@"El Naturalista",
@"Electric Eyewear",
@"Elephantito",
@"Eleven By Venus Williams",
@"Elizabeth And James",
@"Ella Moss",
@"Ellen Tracy",
@"Elliott Lucca",
@"ELSE",
@"Emerica",
@"Emporio Armani",
@"EMU Australia",
@"EPIC Travelgear",
@"EQUIPMENT",
@"Ergobaby",
@"Eric Michael",
@"ESCADA",
@"Ethika",
@"Etnies",
@"Etro",
@"Eva By Eva Franco",
@"Eve Jnr",
@"EVOLV",
@"Exley NB",
@"ExOfficio",
@"Eyebobs",
@"Falke",
@"Fashion Forms",
@"Faviana",
@"Favorite Characters",
@"FDJ French Dressing Jeans",
@"Feetures",
@"Fendi Kids",
@"Fendi Timepieces",
@"Salvatore Ferragamo",
@"FIG Clothing",
@"Filson",
@"Finn Comfort",
@"Fisher Price",
@"FitFlop",
@"Five Ten",
@"Vibram FiveFingers",
@"Fiveloaves Twofish",
@"Fj?Llr?Ven",
@"Flojos",
@"Florsheim",
@"FLY LONDON",
@"Flynn Skye",
@"Foamtreads",
@"Foley & Corinna",
@"Foot Petals",
@"FootJoy",
@"FootMates",
@"For Love And Lemons",
@"Fossil",
@"Fox River",
@"Frances Valentine",
@"Francesco Scognamiglio",
@"Franco Sarto",
@"Fred Perry",
@"Free People",
@"Freebird",
@"Freewaters",
@"French Connection",
@"French Sole",
@"Fresh Produce",
@"Freshly Picked",
@"Frye",
@"Furla",
@"FUZZI",
@"G-Shock",
@"G-Star",
@"G.H. Bass & Co.",
@"Gabor",
@"Gabriela Cadena",
@"Gentle Souls",
@"Georgia Boot",
@"Geox",
@"Giesswein",
@"Giorgio Armani",
@"Giorgio Brutini",
@"Giro",
@"Giuseppe Zanotti",
@"Globe",
@"God's Masterful Children",
@"Gola",
@"Gold & Gravy",
@"Goorin Brothers",
@"Goosecraft",
@"Gordon Rush",
@"Gorjana",
@"Gravati",
@"Grenson",
@"Gucci",
@"GUESS",
@"Haculla",
@"Hadaki",
@"Haflinger",
@"Haiku",
@"Hale",
@"Halston Heritage",
@"Hammitt",
@"Hanky Panky",
@"Hanna Andersson",
@"Hanro",
@"Hard Tail",
@"Hari Mari",
@"Harley-Davidson",
@"Hartmann",
@"Harveys Seatbelt Bag",
@"Hat Attack",
@"Hatley",
@"Havaianas",
@"HEATHER",
@"Hedgren",
@"Heelys",
@"HELM",
@"Herschel Supply Co.",
@"Hestra",
@"Heys America",
@"Hi-Tec",
@"High Sierra",
@"Hispanitas",
@"Hobie",
@"Hobo",
@"Hoka One One",
@"HOOD Rubber Company",
@"Hot Chillys",
@"House Of Harlow",
@"HOUSE OF HOLLAND",
@"Hudson",
@"HUE",
@"HUF",
@"Hunter",
@"Hurley",
@"Hush Puppies",
@"Ilse Jacobsen",
@"Independence Day Clothing Co",
@"Injinji",
@"Inov-8",
@"InterDesign",
@"Irish Setter",
@"Isola",
@"Ivanka Trump",
@"IVY KIRZHNER",
@"J Brand",
@"J. Renee",
@"Jack Rogers",
@"Jack Spade",
@"Jack Wolfskin",
@"Jag Jeans",
@"Jambu",
@"James Campbell",
@"Jamie Sadock",
@"Jane & Bleecker",
@"JanSport",
@"Jantzen",
@"Jason Wu",
@"JBU",
@"Jean Paul Gaultier",
@"Jean Shop",
@"Jefferies Socks",
@"Jeffery-West",
@"Jen's Pirate Booty",
@"Jeremiah",
@"Jeremy Scott",
@"Jerome C. Rousseau",
@"Jerusalem Sandals",
@"Jessica McClintock",
@"Jessica Simpson",
@"JETS By Jessika Allen",
@"Jil Sander Navy",
@"Jil Sander",
@"JILL JILL STUART",
@"Jimmy Choo",
@"JL By Judith Leiber",
@"Jockey",
@"Joe's Jeans",
@"John Deere",
@"John Varvatos",
@"Johnny Was",
@"Johnston & Murphy",
@"Joie",
@"Jonathan Simkhai",
@"Josef Seibel",
@"Josie",
@"Josmo Kids",
@"Ju-Ju-Be",
@"Juicy Couture",
@"Julbo Eyewear",
@"Jumping Jacks Kids",
@"Just Cavalli",
@"Justin",
@"K-Swiss",
@"Kaenon",
@"KAMALIKULTURE By Norma Kamali",
@"Kamik",
@"Kangol",
@"Karen Kane",
@"Karl Lagerfeld Kids",
@"Kate Spade New York",
@"Katy Perry",
@"KAVU",
@"Keds",
@"Keen",
@"KEEPSAKE THE LABEL",
@"Kelsi Dagger Brooklyn",
@"Kelty",
@"KENDALL + KYLIE",
@"Kender West",
@"Kendra Scott",
@"Kennel & Schmenger",
@"Kenneth Cole Reaction",
@"Kenneth Cole",
@"Kenneth Jay Lane",
@"Kensie",
@"Kenzo",
@"Khombu",
@"Kid Express",
@"KINETIX",
@"King Baby Studio",
@"Kipling",
@"Kiyonna",
@"Klogs Footwear",
@"KNOMO London",
@"Kork-Ease",
@"Krazy Larry",
@"Kroon",
@"KUHL",
@"KUT From The Kloth",
@"L'Artiste By Spring Step",
@"L*Space",
@"L.B. Evans",
@"L.K. Bennett",
@"La Blanca",
@"La Canadienne",
@"La Perla",
@"La Sportiva",
@"Lack Of Color",
@"Lacoste",
@"Lakai",
@"LAmade",
@"LAMARQUE",
@"Lanston",
@"Lanvin",
@"Laredo",
@"Laundry By Shelli Segal",
@"LAUREN Ralph Lauren",
@"Le Mystere",
@"Le Specs",
@"Leatherock",
@"LeSportsac",
@"Letarte",
@"Level 99",
@"Levi's?",
@"LFL By Lust For Life",
@"Liebeskind",
@"Life Is Beautiful",
@"Life Is Good",
@"Lifefactory",
@"LifeStride",
@"Lilla P",
@"Lilly Pulitzer",
@"Limi Feu",
@"Linda Farrow Luxe",
@"Linksoul",
@"Lipault Paris",
@"Lisette L Montreal",
@"Little Giraffe",
@"Liverpool",
@"Livie & Luca",
@"LNA",
@"Lodis Accessories",
@"Loeffler Randall",
@"Lole",
@"Lolli LIVING",
@"Lorna Jane",
@"Lotus",
@"Louis Garneau",
@"Louise Et Cie",
@"LOVE Moschino",
@"Love Quotes",
@"Lovers + Friends",
@"Lowa",
@"Lucchese",
@"Lucky Brand",
@"Lucy Love",
@"Lucy",
@"Luli Fama",
@"Lysse",
@"M & F Western",
@"M4D3",
@"Maaji",
@"Maggy London",
@"Magicsuit",
@"Magnanni",
@"Magnum",
@"Majorica",
@"Manduka",
@"Manila Grace",
@"Mara Hoffman",
@"Marc By Marc Jacobs",
@"Marc Fisher LTD",
@"Marc Jacobs",
@"Marc New York By Andrew Marc",
@"Marchesa",
@"Marmot",
@"MARNI",
@"Marsell",
@"Marysia",
@"Massimo Matteo",
@"Matiere",
@"Matisse",
@"Matt Bernson",
@"Maui Jim",
@"Mavi Jeans",
@"MCM",
@"McQ",
@"Me Too",
@"Meli Melo",
@"Members Only",
@"Mephisto",
@"Merrell",
@"Messico",
@"Mezlan",
@"Miansai",
@"Michael Antonio",
@"Michael Bastian Gray Label",
@"Michael Kors",
@"Michael Stars",
@"Michele",
@"MIKOH SWIMWEAR",
@"Mini Melissa",
@"Mini Rodini",
@"Minnetonka",
@"Miraclesuit",
@"Miseno",
@"Missoni",
@"Miu Miu",
@"Miz Mooz",
@"Mizuno",
@"MM6 Maison Margiela",
@"Mod-O-Doc",
@"Monreal London",
@"Montrail",
@"Morgan & Milo Kids",
@"Moschino",
@"Mostly Heard Rarely Seen",
@"Mountain Buggy",
@"Mountain Hardwear",
@"Mountain Khakis",
@"Movado",
@"Mr. Swim",
@"Mud Pie",
@"Munro",
@"Munster Kids",
@"My Flat In London",
@"Naked & Famous",
@"Nally & Millie",
@"NANA JUDY",
@"Nanette Lepore",
@"Naot Footwear",
@"Nathan",
@"Native Eyewear",
@"Native Shoes",
@"Natori",
@"Naturalizer",
@"Naturino",
@"NAU",
@"Nautica",
@"Neil Barrett",
@"New Balance",
@"New Era",
@"NewbarK",
@"Newton Running",
@"Next By Athena",
@"NIC+ZOE",
@"Nicole Miller",
@"Nike",
@"Nina",
@"Nine West",
@"Nixon",
@"NO KA'OI",
@"The North Face",
@"Not Rated",
@"Nunn Bush",
@"Nununu",
@"Nurse Mates",
@"NYDJ",
@"O'Neill",
@"Oakley",
@"Obermeyer",
@"Obey",
@"Oboz",
@"OGIO",
@"Ohw?",
@"Old Friend",
@"Old Gringo",
@"Old Soles",
@"Old West Boots",
@"Oliberte",
@"Oliver Peoples",
@"OluKai",
@"On",
@"Onex",
@"OnGossamer",
@"Onia",
@"Only Hearts",
@"Onzie",
@"OOFOS",
@"Original Penguin",
@"Orla Kiely",
@"Oscar De La Renta",
@"Osiris",
@"Osprey",
@"OTBT",
@"Outdoor Research",
@"P.J. Salvage",
@"Pablosky Kids",
@"Pacsafe",
@"PACT",
@"Paige",
@"Pajar CANADA",
@"Palladium",
@"Pampili",
@"Paradox London Pink",
@"PARC City Boot",
@"Parker Smith",
@"Patricia Green",
@"Patricia Nash",
@"Paul Green",
@"Paul Smith",
@"Pazitos",
@"Pearl Izumi",
@"Pediped",
@"Pedro Garcia",
@"Pelle Moda",
@"Pendleton",
@"Penfield",
@"People Footwear",
@"People's Project LA Kids",
@"Perry Ellis",
@"Persol",
@"Petunia Pickle Bottom",
@"Petzl",
@"PF Flyers",
@"Phil & Teds",
@"Pierre Balmain",
@"Pikolinos",
@"Pistil",
@"PLAE",
@"Plush",
@"Poler",
@"Polo Ralph Lauren",
@"Pomellato 67",
@"Powerstep",
@"Prabal Gurung",
@"Prada",
@"Prana",
@"Preen By Thornton Bregazzi",
@"Pretty Polly",
@"Primigi Kids",
@"Primitive",
@"PRIVATE STOCK",
@"Proenza Schouler",
@"Project Social T",
@"Propet",
@"Publish",
@"PUMA",
@"Pumpkin Patch Kids",
@"Puppies Make Me Happy",
@"QUAY AUSTRALIA",
@"Quiksilver",
@"Rachel Comey",
@"Rachel Kids",
@"Rachel Pally",
@"Rachel Zoe",
@"Racine Carrée",
@"RAEN Optics",
@"Rag & Bone",
@"Ralph Lauren Baby",
@"Randolph",
@"Ray-Ban",
@"RAYE",
@"Rebecca Minkoff",
@"Rebecca Taylor",
@"Red Carter",
@"RED VALENTINO",
@"Red Wing Heritage",
@"Reebok",
@"Reef",
@"Religion",
@"Repetto",
@"Report",
@"Richer Poorer",
@"Rieker",
@"Rimowa",
@"Rip Curl",
@"Roark",
@"Robeez",
@"Robert Clergerie",
@"Robert Graham",
@"Robert Lee Morris",
@"Roberto Cavalli",
@"Roberto Coin",
@"Rochas",
@"Rock And Roll Cowboy",
@"Rock And Roll Cowgirl",
@"Rock Your Baby",
@"Rocket Dog",
@"Rockport",
@"Romika",
@"Roper",
@"Roxy",
@"Royal Robbins",
@"Rsvp",
@"Ruffwear",
@"Rupert Sanderson",
@"RVCA",
@"Ryka",
@"Saint Laurent",
@"SALEWA",
@"Salomon",
@"Salt Water Sandal By Hoy Shoes",
@"Salvatore Ferragamo",
@"Sam Edelman",
@"Samsonite",
@"San Diego Hat Company",
@"Sanctuary",
@"Sanita",
@"Sanuk",
@"Satorisan",
@"Saucony",
@"Save The Duck",
@"SAXX UNDERWEAR",
@"Sbicca",
@"SCALA",
@"Scarpa",
@"School Issue",
@"Scotch & Soda",
@"Scott Hawaii",
@"Scully",
@"Seafolly",
@"SeaVees",
@"Sebago",
@"See By Chloe",
@"See Kai Run Kids",
@"Seirus",
@"Sergio Rossi",
@"Seychelles",
@"Shellys London",
@"Sherpani",
@"Shimano",
@"Shinola Detroit",
@"Shock Absorber",
@"Show Me Your Mumu",
@"Shwood",
@"Sigerson Morrison",
@"Simple",
@"SJP By Sarah Jessica Parker",
@"Skagen",
@"Skarlett Blue",
@"SKECHERS",
@"Skip Hop",
@"Skirt Sports",
@"Smartwool",
@"Smith Optics",
@"Socksmith",
@"Sof Sole",
@"Sofft",
@"Soft Style",
@"SoftWalk",
@"Sol Sana",
@"SOLE",
@"Solemates",
@"Soleus",
@"SOLO",
@"Soludos",
@"Sonia By Sonia Rykiel",
@"Sonia Rykiel Kids",
@"SOREL",
@"Soybu",
@"Spanx",
@"Speedo",
@"Spenco",
@"Sperry",
@"Spira",
@"Spiritual Gangster",
@"Splendid",
@"Sportmax",
@"Spring Step",
@"Spy Optic",
@"Spyder",
@"Stacy Adams",
@"Stance",
@"Stella McCartney",
@"Stephen Webster",
@"Stetson",
@"Steve Madden",
@"Stonewear Designs",
@"Stonz",
@"Stride Rite",
@"STS Ranchwear",
@"Stuart Weitzman",
@"Suecomma Bonnie",
@"Summit By White Mountain",
@"SunCloud Polarized Optics",
@"Super",
@"Superfeet",
@"Superga",
@"Supra",
@"Susana Monaco",
@"Suunto",
@"Swarovski",
@"Swedish Hasbeens",
@"Tabitha Simmons",
@"Tahari By ASL",
@"Tahari",
@"Tamaris",
@"Taos Footwear",
@"Tart",
@"Tasc Performance",
@"Tasha Polizzi",
@"Tavik",
@"Tecnica",
@"Ted Baker",
@"Teeki",
@"Tempur-Pedic",
@"Teva",
@"The FLEXX",
@"The Jetset Diaries",
@"The Kooples",
@"The North Face",
@"The Original Retro Brand",
@"The Sak",
@"The Unbranded Brand",
@"Theory",
@"THERAFIT",
@"Think!",
@"Thirtytwo",
@"Thomas Dean & Co.",
@"THOMAS WYLDE",
@"Thorlos",
@"Thorogood",
@"Threads 4 Thought",
@"Three Dots",
@"Tifosi Optics",
@"Timberland",
@"Timbuk2",
@"Timex",
@"TKEES",
@"To Boot New York",
@"Toad & Co",
@"Todd Snyder",
@"Toesox",
@"Toga Pulla",
@"Tolani",
@"Tommy Bahama",
@"Tommy Hilfiger",
@"TOMS",
@"Toni Pons",
@"Toobydoo",
@"Topo Designs",
@"Torino Leather Co.",
@"Tory Burch",
@"Touch Ups",
@"Trafalgar",
@"Trask",
@"Travelpro",
@"TravisMathew",
@"Tretorn",
@"Tribal",
@"TriggerPoint",
@"Trimfit",
@"Trina Turk",
@"Trotters",
@"True Grit",
@"True Religion",
@"Tsukihoshi Kids",
@"Tubbs",
@"Tumi",
@"Tundra Boots",
@"TYR",
@"UGG",
@"Ultimate Direction",
@"Umi Kids",
@"Under Armour",
@"Union Of Angels",
@"Union",
@"Unique Vintage",
@"United By Blue",
@"Us Angels",
@"Valentino",
@"Vaneli",
@"Vanessa Mooney",
@"Vans",
@"Vasque",
@"Vera Bradley",
@"Vera Wang",
@"Veronique Branquihno",
@"Versace",
@"Vestal",
@"Via Spiga",
@"Vibram FiveFingers",
@"Victorinox",
@"Vilebrequin",
@"Vince Camuto",
@"Vince",
@"Vineyard Vines",
@"Vintage 1946",
@"VIONIC",
@"VISSLA",
@"Vitamin A Swimwear",
@"Vivienne Westwood",
@"Vivobarefoot",
@"VOLATILE",
@"Volcom",
@"Volley Australia",
@"VonZipper",
@"W6YZ",
@"Wacoal",
@"Walking Cradles",
@"Warm Creature",
@"Stuart Weitzman",
@"Western Chief Kids",
@"Wigwam",
@"Will Leather Goods",
@"Wilson",
@"Wolford",
@"Wolky",
@"Wolverine",
@"Woodlore",
@"Woolrich",
@"Wrightsock",
@"XCVI",
@"Y's By Yohji Yamamoto",
@"YakTrax",
@"Yellow Box",
@"YIGAL AZROU?L",
@"Yosi Samra",
@"Young Fabulous & Broke",
@"Yummie By Heather Thomson",
@"1.STATE",
@"2(X)IST",
@"2XU",
@"3.1 Phillip Lim",
@"34 Heritage",
@"4Ward Clothing",
@"5.11 Tactical",
@"6 Shore Road By Pooja",
@"7 Diamonds",
@"7 For All Mankind"
];}
    return _shoesList;

}

- (NSArray*)shoesURLList{
    if (!_shoesURLList) {
    //     _shoesURLList = @[@[@"cn.fmnii.com"],@[@"cn.fmnii.com",@"shoes"],@[@"cn.fmnii.com",@"clothes"],@[@"cn.fmnii.com",@"bags"],@[@"cn.fmnii.com",@"info"],@[@"cn.fmnii.com",@"newmaterial"]];
    // }
  _shoesURLList =  @[
@[@"cn.fmnii.com",@"atestoni"],
@[@"cn.fmnii.com",@"Acorn"],
@[@"cn.fmnii.com",@"ADA Collection"],
@[@"cn.fmnii.com",@"Adelyn Rae"],
@[@"cn.fmnii.com",@"Aden + Anais"],
@[@"cn.fmnii.com",@"Adidas"],
@[@"cn.fmnii.com",@"Adrianna Papell"],
@[@"cn.fmnii.com",@"Aerosoles"],
@[@"cn.fmnii.com",@"Aetrex"],
@[@"cn.fmnii.com",@"AG Adriano Goldschmied"],
@[@"cn.fmnii.com",@"Agave Denim"],
@[@"cn.fmnii.com",@"Agent Provocateur"],
@[@"cn.fmnii.com",@"Agua De Coco By Liana Thomaz"],
@[@"cn.fmnii.com",@"Ahnu"],
@[@"cn.fmnii.com",@"Aidan Mattox"],
@[@"cn.fmnii.com",@"AIGLE"],
@[@"cn.fmnii.com",@"AKID Brand"],
@[@"cn.fmnii.com",@"Akomplice"],
@[@"cn.fmnii.com",@"Alberta Ferretti"],
@[@"cn.fmnii.com",@"ALDO"],
@[@"cn.fmnii.com",@"Alegria"],
@[@"cn.fmnii.com",@"Alex And Ani"],
@[@"cn.fmnii.com",@"Alexander McQueen"],
@[@"cn.fmnii.com",@"Alexis Bittar"],
@[@"cn.fmnii.com",@"Alice + Olivia"],
@[@"cn.fmnii.com",@"Allen Allen"],
@[@"cn.fmnii.com",@"Allen-Edmonds"],
@[@"cn.fmnii.com",@"ALO"],
@[@"cn.fmnii.com",@"Alpha Industries"],
@[@"cn.fmnii.com",@"Alternative"],
@[@"cn.fmnii.com",@"Altra Footwear"],
@[@"cn.fmnii.com",@"AmeriBag, Inc."],
@[@"cn.fmnii.com",@"American Fighter"],
@[@"cn.fmnii.com",@"American West"],
@[@"cn.fmnii.com",@"Amiana"],
@[@"cn.fmnii.com",@"Amuse Society"],
@[@"cn.fmnii.com",@"AND1"],
@[@"cn.fmnii.com",@"Andre Assous"],
@[@"cn.fmnii.com",@"Anita"],
@[@"cn.fmnii.com",@"Anne Klein New York"],
@[@"cn.fmnii.com",@"Anne Klein"],
@[@"cn.fmnii.com",@"Anuschka Handbags"],
@[@"cn.fmnii.com",@"Appaman Kids"],
@[@"cn.fmnii.com",@"Aquatalia"],
@[@"cn.fmnii.com",@"Ara"],
@[@"cn.fmnii.com",@"Aravon"],
@[@"cn.fmnii.com",@"Arc'teryx"],
@[@"cn.fmnii.com",@"Arche"],
@[@"cn.fmnii.com",@"Arcopedico"],
@[@"cn.fmnii.com",@"Ariat"],
@[@"cn.fmnii.com",@"Armani Junior"],
@[@"cn.fmnii.com",@"ASH"],
@[@"cn.fmnii.com",@"ASICS"],
@[@"cn.fmnii.com",@"ASKA"],
@[@"cn.fmnii.com",@"Asolo"],
@[@"cn.fmnii.com",@"ASTR The Label"],
@[@"cn.fmnii.com",@"Athena Alexander"],
@[@"cn.fmnii.com",@"Athena"],
@[@"cn.fmnii.com",@"Athletic Propulsion Labs (APL)"],
@[@"cn.fmnii.com",@"Atlas"],
@[@"cn.fmnii.com",@"ATM Anthony Thomas Melillo"],
@[@"cn.fmnii.com",@"Aventura Clothing"],
@[@"cn.fmnii.com",@"B"],
@[@"cn.fmnii.com",@"B Brian Atwood"],
@[@"cn.fmnii.com",@"B Collection By Bobeau"],
@[@"cn.fmnii.com",@"B.Tempt'd"],
@[@"cn.fmnii.com",@"Babiators"],
@[@"cn.fmnii.com",@"Baby Deer"],
@[@"cn.fmnii.com",@"Baby Jogger"],
@[@"cn.fmnii.com",@"BabyBjorn"],
@[@"cn.fmnii.com",@"Bacco Bucci"],
@[@"cn.fmnii.com",@"Badgley Mischka"],
@[@"cn.fmnii.com",@"Baffin"],
@[@"cn.fmnii.com",@"Baggallini"],
@[@"cn.fmnii.com",@"Bailey Of Hollywood"],
@[@"cn.fmnii.com",@"Balenciaga"],
@[@"cn.fmnii.com",@"Bally"],
@[@"cn.fmnii.com",@"Bandolino"],
@[@"cn.fmnii.com",@"Base London"],
@[@"cn.fmnii.com",@"Bates Footwear"],
@[@"cn.fmnii.com",@"BB Dakota"],
@[@"cn.fmnii.com",@"BCBGeneration"],
@[@"cn.fmnii.com",@"BCBGMAXAZRIA"],
@[@"cn.fmnii.com",@"Bebe Au Lait"],
@[@"cn.fmnii.com",@"BECCA By Rebecca Virtue"],
@[@"cn.fmnii.com",@"Bed Stu"],
@[@"cn.fmnii.com",@"BedHead"],
@[@"cn.fmnii.com",@"Bedroom Athletics"],
@[@"cn.fmnii.com",@"Bella-Vita"],
@[@"cn.fmnii.com",@"BELSTAFF"],
@[@"cn.fmnii.com",@"Ben Sherman"],
@[@"cn.fmnii.com",@"Bernardo"],
@[@"cn.fmnii.com",@"Bernie Mev."],
@[@"cn.fmnii.com",@"Betmar"],
@[@"cn.fmnii.com",@"Betsey Johnson"],
@[@"cn.fmnii.com",@"Beyond Yoga"],
@[@"cn.fmnii.com",@"Big Agnes"],
@[@"cn.fmnii.com",@"Billabong"],
@[@"cn.fmnii.com",@"Billy Reid"],
@[@"cn.fmnii.com",@"Bindya"],
@[@"cn.fmnii.com",@"Bionica"],
@[@"cn.fmnii.com",@"Birkenstock"],
@[@"cn.fmnii.com",@"Bishop + Young"],
@[@"cn.fmnii.com",@"Black Diamond"],
@[@"cn.fmnii.com",@"Blanc Noir"],
@[@"cn.fmnii.com",@"Blank NYC"],
@[@"cn.fmnii.com",@"Bleu Rod Beattie"],
@[@"cn.fmnii.com",@"Bloch"],
@[@"cn.fmnii.com",@"Blondo"],
@[@"cn.fmnii.com",@"Blowfish"],
@[@"cn.fmnii.com",@"Blue Life"],
@[@"cn.fmnii.com",@"Blundstone"],
@[@"cn.fmnii.com",@"Bobux Kids"],
@[@"cn.fmnii.com",@"Body Glove"],
@[@"cn.fmnii.com",@"Bogner Fire + Ice"],
@[@"cn.fmnii.com",@"Bogs"],
@[@"cn.fmnii.com",@"BOOTIGHTS"],
@[@"cn.fmnii.com",@"Born"],
@[@"cn.fmnii.com",@"Bosca"],
@[@"cn.fmnii.com",@"BOSS Hugo Boss"],
@[@"cn.fmnii.com",@"Bostonian"],
@[@"cn.fmnii.com",@"Botkier"],
@[@"cn.fmnii.com",@"Boutique Moschino"],
@[@"cn.fmnii.com",@"Bowie X James"],
@[@"cn.fmnii.com",@"Brahmin"],
@[@"cn.fmnii.com",@"Bric's Milano"],
@[@"cn.fmnii.com",@"Briggs & Riley"],
@[@"cn.fmnii.com",@"Brighton"],
@[@"cn.fmnii.com",@"Brigitte Bailey"],
@[@"cn.fmnii.com",@"Brixton"],
@[@"cn.fmnii.com",@"Brooks"],
@[@"cn.fmnii.com",@"Bruno Magli"],
@[@"cn.fmnii.com",@"Buffalo David Bitton"],
@[@"cn.fmnii.com",@"BUGATCHI"],
@[@"cn.fmnii.com",@"BULA"],
@[@"cn.fmnii.com",@"Bulova"],
@[@"cn.fmnii.com",@"Burberry"],
@[@"cn.fmnii.com",@"Burton"],
@[@"cn.fmnii.com",@"C"],
@[@"cn.fmnii.com",@"C & C California"],
@[@"cn.fmnii.com",@"Call It SPRING"],
@[@"cn.fmnii.com",@"Callaway"],
@[@"cn.fmnii.com",@"Calou Stockholm"],
@[@"cn.fmnii.com",@"Calvin Klein"],
@[@"cn.fmnii.com",@"CamelBak"],
@[@"cn.fmnii.com",@"Camper"],
@[@"cn.fmnii.com",@"Caparros"],
@[@"cn.fmnii.com",@"Capezio"],
@[@"cn.fmnii.com",@"Captain Fin"],
@[@"cn.fmnii.com",@"Carhartt"],
@[@"cn.fmnii.com",@"CARLOS By Carlos Santana"],
@[@"cn.fmnii.com",@"Carole Hochman"],
@[@"cn.fmnii.com",@"Carolina"],
@[@"cn.fmnii.com",@"Carrera"],
@[@"cn.fmnii.com",@"Carrucci"],
@[@"cn.fmnii.com",@"Carve Designs"],
@[@"cn.fmnii.com",@"Cashmere In Love"],
@[@"cn.fmnii.com",@"Caterpillar"],
@[@"cn.fmnii.com",@"CATHERINE Catherine Malandrino"],
@[@"cn.fmnii.com",@"CeCe"],
@[@"cn.fmnii.com",@"Celtek"],
@[@"cn.fmnii.com",@"Chaco"],
@[@"cn.fmnii.com",@"Champion"],
@[@"cn.fmnii.com",@"Chan Luu"],
@[@"cn.fmnii.com",@"Charles By Charles David"],
@[@"cn.fmnii.com",@"Charlotte Olympia"],
@[@"cn.fmnii.com",@"Chaser Kids"],
@[@"cn.fmnii.com",@"Chicago Skates"],
@[@"cn.fmnii.com",@"Chinese Laundry"],
@[@"cn.fmnii.com",@"Chippewa"],
@[@"cn.fmnii.com",@"CHLOE GOSSELIN"],
@[@"cn.fmnii.com",@"Chloe"],
@[@"cn.fmnii.com",@"Chooka"],
@[@"cn.fmnii.com",@"CHOOZE"],
@[@"cn.fmnii.com",@"Christin Michaels"],
@[@"cn.fmnii.com",@"Chrome"],
@[@"cn.fmnii.com",@"Cienta Kids Shoes"],
@[@"cn.fmnii.com",@"Cinch"],
@[@"cn.fmnii.com",@"Circa"],
@[@"cn.fmnii.com",@"Citizen Watches"],
@[@"cn.fmnii.com",@"Clarks"],
@[@"cn.fmnii.com",@"Clayton"],
@[@"cn.fmnii.com",@"Clear Weather"],
@[@"cn.fmnii.com",@"COACH"],
@[@"cn.fmnii.com",@"Coal"],
@[@"cn.fmnii.com",@"Cobian"],
@[@"cn.fmnii.com",@"Cole Haan"],
@[@"cn.fmnii.com",@"Columbia"],
@[@"cn.fmnii.com",@"Comfortiva"],
@[@"cn.fmnii.com",@"Commando"],
@[@"cn.fmnii.com",@"Converse"],
@[@"cn.fmnii.com",@"Coobie"],
@[@"cn.fmnii.com",@"Coolway"],
@[@"cn.fmnii.com",@"Cordani"],
@[@"cn.fmnii.com",@"Corral Boots"],
@[@"cn.fmnii.com",@"Corso Como"],
@[@"cn.fmnii.com",@"Cosabella"],
@[@"cn.fmnii.com",@"Cosatto"],
@[@"cn.fmnii.com",@"Costa"],
@[@"cn.fmnii.com",@"COWBOYSBELT"],
@[@"cn.fmnii.com",@"Crabbyclaws"],
@[@"cn.fmnii.com",@"Creative Recreation"],
@[@"cn.fmnii.com",@"Crocs"],
@[@"cn.fmnii.com",@"Crosby Square"],
@[@"cn.fmnii.com",@"Cruel"],
@[@"cn.fmnii.com",@"Cufflinks Inc."],
@[@"cn.fmnii.com",@"Culture Phit"],
@[@"cn.fmnii.com",@"Custom Ketchup"],
@[@"cn.fmnii.com",@"CW-X"],
@[@"cn.fmnii.com",@"Cycleur De Luxe"],
@[@"cn.fmnii.com",@"Cote & Ciel"],
@[@"cn.fmnii.com",@"D"],
@[@"cn.fmnii.com",@"D.GNAK"],
@[@"cn.fmnii.com",@"Dakine"],
@[@"cn.fmnii.com",@"Dale Of Norway"],
@[@"cn.fmnii.com",@"Dan Post"],
@[@"cn.fmnii.com",@"Daniel Green"],
@[@"cn.fmnii.com",@"Danner"],
@[@"cn.fmnii.com",@"DANNIJO"],
@[@"cn.fmnii.com",@"Dansko"],
@[@"cn.fmnii.com",@"David Tate"],
@[@"cn.fmnii.com",@"DBYD"],
@[@"cn.fmnii.com",@"DC"],
@[@"cn.fmnii.com",@"Dee Berkley"],
@[@"cn.fmnii.com",@"Deer Stags"],
@[@"cn.fmnii.com",@"Del Toro"],
@[@"cn.fmnii.com",@"Delsey"],
@[@"cn.fmnii.com",@"Depressed Monsters"],
@[@"cn.fmnii.com",@"Deuter"],
@[@"cn.fmnii.com",@"Dexter"],
@[@"cn.fmnii.com",@"Diadora"],
@[@"cn.fmnii.com",@"Diane Von Furstenberg"],
@[@"cn.fmnii.com",@"Diesel"],
@[@"cn.fmnii.com",@"Dingo"],
@[@"cn.fmnii.com",@"DKNY"],
@[@"cn.fmnii.com",@"DL1961"],
@[@"cn.fmnii.com",@"Dockers"],
@[@"cn.fmnii.com",@"Dogeared"],
@[@"cn.fmnii.com",@"Dolce & Gabbana"],
@[@"cn.fmnii.com",@"Dolce Vita"],
@[@"cn.fmnii.com",@"Donald J Pliner"],
@[@"cn.fmnii.com",@"Donna Morgan"],
@[@"cn.fmnii.com",@"Dooney & Bourke"],
@[@"cn.fmnii.com",@"Double D Ranchwear"],
@[@"cn.fmnii.com",@"Doucal's"],
@[@"cn.fmnii.com",@"Dr. Martens"],
@[@"cn.fmnii.com",@"Dr. Scholl's"],
@[@"cn.fmnii.com",@"Dragon Alliance"],
@[@"cn.fmnii.com",@"Drew"],
@[@"cn.fmnii.com",@"Drymax Sport"],
@[@"cn.fmnii.com",@"DSQUARED2"],
@[@"cn.fmnii.com",@"Dunham"],
@[@"cn.fmnii.com",@"Durango"],
@[@"cn.fmnii.com",@"DUVETICA"],
@[@"cn.fmnii.com",@"Dylan By True Grit"],
@[@"cn.fmnii.com",@"E"],
@[@"cn.fmnii.com",@"Eagle Creek"],
@[@"cn.fmnii.com",@"Earth"],
@[@"cn.fmnii.com",@"Eastland 1955"],
@[@"cn.fmnii.com",@"Easy Spirit"],
@[@"cn.fmnii.com",@"ECCO"],
@[@"cn.fmnii.com",@"Echo"],
@[@"cn.fmnii.com",@"Ecoths"],
@[@"cn.fmnii.com",@"ED Ellen DeGeneres"],
@[@"cn.fmnii.com",@"Eileen Fisher"],
@[@"cn.fmnii.com",@"Eileen West"],
@[@"cn.fmnii.com",@"El Naturalista"],
@[@"cn.fmnii.com",@"Electric Eyewear"],
@[@"cn.fmnii.com",@"Elephantito"],
@[@"cn.fmnii.com",@"Eleven By Venus Williams"],
@[@"cn.fmnii.com",@"Elizabeth And James"],
@[@"cn.fmnii.com",@"Ella Moss"],
@[@"cn.fmnii.com",@"Ellen Tracy"],
@[@"cn.fmnii.com",@"Elliott Lucca"],
@[@"cn.fmnii.com",@"ELSE"],
@[@"cn.fmnii.com",@"Emerica"],
@[@"cn.fmnii.com",@"Emporio Armani"],
@[@"cn.fmnii.com",@"EMU Australia"],
@[@"cn.fmnii.com",@"EPIC Travelgear"],
@[@"cn.fmnii.com",@"EQUIPMENT"],
@[@"cn.fmnii.com",@"Ergobaby"],
@[@"cn.fmnii.com",@"Eric Michael"],
@[@"cn.fmnii.com",@"ESCADA"],
@[@"cn.fmnii.com",@"Ethika"],
@[@"cn.fmnii.com",@"Etnies"],
@[@"cn.fmnii.com",@"Etro"],
@[@"cn.fmnii.com",@"Eva By Eva Franco"],
@[@"cn.fmnii.com",@"Eve Jnr"],
@[@"cn.fmnii.com",@"EVOLV"],
@[@"cn.fmnii.com",@"Exley NB"],
@[@"cn.fmnii.com",@"ExOfficio"],
@[@"cn.fmnii.com",@"Eyebobs"],
@[@"cn.fmnii.com",@"F"],
@[@"cn.fmnii.com",@"Falke"],
@[@"cn.fmnii.com",@"Fashion Forms"],
@[@"cn.fmnii.com",@"Faviana"],
@[@"cn.fmnii.com",@"Favorite Characters"],
@[@"cn.fmnii.com",@"FDJ French Dressing Jeans"],
@[@"cn.fmnii.com",@"Feetures"],
@[@"cn.fmnii.com",@"Fendi Kids"],
@[@"cn.fmnii.com",@"Fendi Timepieces"],
@[@"cn.fmnii.com",@"Salvatore Ferragamo"],
@[@"cn.fmnii.com",@"FIG Clothing"],
@[@"cn.fmnii.com",@"Filson"],
@[@"cn.fmnii.com",@"Finn Comfort"],
@[@"cn.fmnii.com",@"Fisher Price"],
@[@"cn.fmnii.com",@"FitFlop"],
@[@"cn.fmnii.com",@"Five Ten"],
@[@"cn.fmnii.com",@"Vibram FiveFingers"],
@[@"cn.fmnii.com",@"Fiveloaves Twofish"],
@[@"cn.fmnii.com",@"Fj?Llr?Ven"],
@[@"cn.fmnii.com",@"Flojos"],
@[@"cn.fmnii.com",@"Florsheim"],
@[@"cn.fmnii.com",@"FLY LONDON"],
@[@"cn.fmnii.com",@"Flynn Skye"],
@[@"cn.fmnii.com",@"Foamtreads"],
@[@"cn.fmnii.com",@"Foley & Corinna"],
@[@"cn.fmnii.com",@"Foot Petals"],
@[@"cn.fmnii.com",@"FootJoy"],
@[@"cn.fmnii.com",@"FootMates"],
@[@"cn.fmnii.com",@"For Love And Lemons"],
@[@"cn.fmnii.com",@"Fossil"],
@[@"cn.fmnii.com",@"Fox River"],
@[@"cn.fmnii.com",@"Frances Valentine"],
@[@"cn.fmnii.com",@"Francesco Scognamiglio"],
@[@"cn.fmnii.com",@"Franco Sarto"],
@[@"cn.fmnii.com",@"Fred Perry"],
@[@"cn.fmnii.com",@"Free People"],
@[@"cn.fmnii.com",@"Freebird"],
@[@"cn.fmnii.com",@"Freewaters"],
@[@"cn.fmnii.com",@"French Connection"],
@[@"cn.fmnii.com",@"French Sole"],
@[@"cn.fmnii.com",@"Fresh Produce"],
@[@"cn.fmnii.com",@"Freshly Picked"],
@[@"cn.fmnii.com",@"Frye"],
@[@"cn.fmnii.com",@"Furla"],
@[@"cn.fmnii.com",@"FUZZI"],
@[@"cn.fmnii.com",@"G"],
@[@"cn.fmnii.com",@"G-Shock"],
@[@"cn.fmnii.com",@"G-Star"],
@[@"cn.fmnii.com",@"G.H. Bass & Co."],
@[@"cn.fmnii.com",@"Gabor"],
@[@"cn.fmnii.com",@"Gabriela Cadena"],
@[@"cn.fmnii.com",@"Gentle Souls"],
@[@"cn.fmnii.com",@"Georgia Boot"],
@[@"cn.fmnii.com",@"Geox"],
@[@"cn.fmnii.com",@"Giesswein"],
@[@"cn.fmnii.com",@"Giorgio Armani"],
@[@"cn.fmnii.com",@"Giorgio Brutini"],
@[@"cn.fmnii.com",@"Giro"],
@[@"cn.fmnii.com",@"Giuseppe Zanotti"],
@[@"cn.fmnii.com",@"Globe"],
@[@"cn.fmnii.com",@"God's Masterful Children"],
@[@"cn.fmnii.com",@"Gola"],
@[@"cn.fmnii.com",@"Gold & Gravy"],
@[@"cn.fmnii.com",@"Goorin Brothers"],
@[@"cn.fmnii.com",@"Goosecraft"],
@[@"cn.fmnii.com",@"Gordon Rush"],
@[@"cn.fmnii.com",@"Gorjana"],
@[@"cn.fmnii.com",@"Gravati"],
@[@"cn.fmnii.com",@"Grenson"],
@[@"cn.fmnii.com",@"Gucci"],
@[@"cn.fmnii.com",@"GUESS"],
@[@"cn.fmnii.com",@"H"],
@[@"cn.fmnii.com",@"Haculla"],
@[@"cn.fmnii.com",@"Hadaki"],
@[@"cn.fmnii.com",@"Haflinger"],
@[@"cn.fmnii.com",@"Haiku"],
@[@"cn.fmnii.com",@"Hale"],
@[@"cn.fmnii.com",@"Halston Heritage"],
@[@"cn.fmnii.com",@"Hammitt"],
@[@"cn.fmnii.com",@"Hanky Panky"],
@[@"cn.fmnii.com",@"Hanna Andersson"],
@[@"cn.fmnii.com",@"Hanro"],
@[@"cn.fmnii.com",@"Hard Tail"],
@[@"cn.fmnii.com",@"Hari Mari"],
@[@"cn.fmnii.com",@"Harley-Davidson"],
@[@"cn.fmnii.com",@"Hartmann"],
@[@"cn.fmnii.com",@"Harveys Seatbelt Bag"],
@[@"cn.fmnii.com",@"Hat Attack"],
@[@"cn.fmnii.com",@"Hatley"],
@[@"cn.fmnii.com",@"Havaianas"],
@[@"cn.fmnii.com",@"HEATHER"],
@[@"cn.fmnii.com",@"Hedgren"],
@[@"cn.fmnii.com",@"Heelys"],
@[@"cn.fmnii.com",@"HELM"],
@[@"cn.fmnii.com",@"Herschel Supply Co."],
@[@"cn.fmnii.com",@"Hestra"],
@[@"cn.fmnii.com",@"Heys America"],
@[@"cn.fmnii.com",@"Hi-Tec"],
@[@"cn.fmnii.com",@"High Sierra"],
@[@"cn.fmnii.com",@"Hispanitas"],
@[@"cn.fmnii.com",@"Hobie"],
@[@"cn.fmnii.com",@"Hobo"],
@[@"cn.fmnii.com",@"Hoka One One"],
@[@"cn.fmnii.com",@"HOOD Rubber Company"],
@[@"cn.fmnii.com",@"Hot Chillys"],
@[@"cn.fmnii.com",@"House Of Harlow"],
@[@"cn.fmnii.com",@"HOUSE OF HOLLAND"],
@[@"cn.fmnii.com",@"Hudson"],
@[@"cn.fmnii.com",@"HUE"],
@[@"cn.fmnii.com",@"HUF"],
@[@"cn.fmnii.com",@"Hunter"],
@[@"cn.fmnii.com",@"Hurley"],
@[@"cn.fmnii.com",@"Hush Puppies"],
@[@"cn.fmnii.com",@"I"],
@[@"cn.fmnii.com",@"Ilse Jacobsen"],
@[@"cn.fmnii.com",@"Independence Day Clothing Co"],
@[@"cn.fmnii.com",@"Injinji"],
@[@"cn.fmnii.com",@"Inov-8"],
@[@"cn.fmnii.com",@"InterDesign"],
@[@"cn.fmnii.com",@"Irish Setter"],
@[@"cn.fmnii.com",@"Isola"],
@[@"cn.fmnii.com",@"Ivanka Trump"],
@[@"cn.fmnii.com",@"IVY KIRZHNER"],
@[@"cn.fmnii.com",@"J"],
@[@"cn.fmnii.com",@"J Brand"],
@[@"cn.fmnii.com",@"J. Renee"],
@[@"cn.fmnii.com",@"Jack Rogers"],
@[@"cn.fmnii.com",@"Jack Spade"],
@[@"cn.fmnii.com",@"Jack Wolfskin"],
@[@"cn.fmnii.com",@"Jag Jeans"],
@[@"cn.fmnii.com",@"Jambu"],
@[@"cn.fmnii.com",@"James Campbell"],
@[@"cn.fmnii.com",@"Jamie Sadock"],
@[@"cn.fmnii.com",@"Jane & Bleecker"],
@[@"cn.fmnii.com",@"JanSport"],
@[@"cn.fmnii.com",@"Jantzen"],
@[@"cn.fmnii.com",@"Jason Wu"],
@[@"cn.fmnii.com",@"JBU"],
@[@"cn.fmnii.com",@"Jean Paul Gaultier"],
@[@"cn.fmnii.com",@"Jean Shop"],
@[@"cn.fmnii.com",@"Jefferies Socks"],
@[@"cn.fmnii.com",@"Jeffery-West"],
@[@"cn.fmnii.com",@"Jen's Pirate Booty"],
@[@"cn.fmnii.com",@"Jeremiah"],
@[@"cn.fmnii.com",@"Jeremy Scott"],
@[@"cn.fmnii.com",@"Jerome C. Rousseau"],
@[@"cn.fmnii.com",@"Jerusalem Sandals"],
@[@"cn.fmnii.com",@"Jessica McClintock"],
@[@"cn.fmnii.com",@"Jessica Simpson"],
@[@"cn.fmnii.com",@"JETS By Jessika Allen"],
@[@"cn.fmnii.com",@"Jil Sander Navy"],
@[@"cn.fmnii.com",@"Jil Sander"],
@[@"cn.fmnii.com",@"JILL JILL STUART"],
@[@"cn.fmnii.com",@"Jimmy Choo"],
@[@"cn.fmnii.com",@"JL By Judith Leiber"],
@[@"cn.fmnii.com",@"Jockey"],
@[@"cn.fmnii.com",@"Joe's Jeans"],
@[@"cn.fmnii.com",@"John Deere"],
@[@"cn.fmnii.com",@"John Varvatos"],
@[@"cn.fmnii.com",@"Johnny Was"],
@[@"cn.fmnii.com",@"Johnston & Murphy"],
@[@"cn.fmnii.com",@"Joie"],
@[@"cn.fmnii.com",@"Jonathan Simkhai"],
@[@"cn.fmnii.com",@"Josef Seibel"],
@[@"cn.fmnii.com",@"Josie"],
@[@"cn.fmnii.com",@"Josmo Kids"],
@[@"cn.fmnii.com",@"Ju-Ju-Be"],
@[@"cn.fmnii.com",@"Juicy Couture"],
@[@"cn.fmnii.com",@"Julbo Eyewear"],
@[@"cn.fmnii.com",@"Jumping Jacks Kids"],
@[@"cn.fmnii.com",@"Just Cavalli"],
@[@"cn.fmnii.com",@"Justin"],
@[@"cn.fmnii.com",@"K"],
@[@"cn.fmnii.com",@"K-Swiss"],
@[@"cn.fmnii.com",@"Kaenon"],
@[@"cn.fmnii.com",@"KAMALIKULTURE By Norma Kamali"],
@[@"cn.fmnii.com",@"Kamik"],
@[@"cn.fmnii.com",@"Kangol"],
@[@"cn.fmnii.com",@"Karen Kane"],
@[@"cn.fmnii.com",@"Karl Lagerfeld Kids"],
@[@"cn.fmnii.com",@"Kate Spade New York"],
@[@"cn.fmnii.com",@"Katy Perry"],
@[@"cn.fmnii.com",@"KAVU"],
@[@"cn.fmnii.com",@"Keds"],
@[@"cn.fmnii.com",@"Keen"],
@[@"cn.fmnii.com",@"KEEPSAKE THE LABEL"],
@[@"cn.fmnii.com",@"Kelsi Dagger Brooklyn"],
@[@"cn.fmnii.com",@"Kelty"],
@[@"cn.fmnii.com",@"KENDALL + KYLIE"],
@[@"cn.fmnii.com",@"Kender West"],
@[@"cn.fmnii.com",@"Kendra Scott"],
@[@"cn.fmnii.com",@"Kennel & Schmenger"],
@[@"cn.fmnii.com",@"Kenneth Cole Reaction"],
@[@"cn.fmnii.com",@"Kenneth Cole"],
@[@"cn.fmnii.com",@"Kenneth Jay Lane"],
@[@"cn.fmnii.com",@"Kensie"],
@[@"cn.fmnii.com",@"Kenzo"],
@[@"cn.fmnii.com",@"Khombu"],
@[@"cn.fmnii.com",@"Kid Express"],
@[@"cn.fmnii.com",@"KINETIX"],
@[@"cn.fmnii.com",@"King Baby Studio"],
@[@"cn.fmnii.com",@"Kipling"],
@[@"cn.fmnii.com",@"Kiyonna"],
@[@"cn.fmnii.com",@"Klogs Footwear"],
@[@"cn.fmnii.com",@"KNOMO London"],
@[@"cn.fmnii.com",@"Kork-Ease"],
@[@"cn.fmnii.com",@"Krazy Larry"],
@[@"cn.fmnii.com",@"Kroon"],
@[@"cn.fmnii.com",@"KUHL"],
@[@"cn.fmnii.com",@"KUT From The Kloth"],
@[@"cn.fmnii.com",@"L"],
@[@"cn.fmnii.com",@"L'Artiste By Spring Step"],
@[@"cn.fmnii.com",@"L*Space"],
@[@"cn.fmnii.com",@"L.B. Evans"],
@[@"cn.fmnii.com",@"L.K. Bennett"],
@[@"cn.fmnii.com",@"La Blanca"],
@[@"cn.fmnii.com",@"La Canadienne"],
@[@"cn.fmnii.com",@"La Perla"],
@[@"cn.fmnii.com",@"La Sportiva"],
@[@"cn.fmnii.com",@"Lack Of Color"],
@[@"cn.fmnii.com",@"Lacoste"],
@[@"cn.fmnii.com",@"Lakai"],
@[@"cn.fmnii.com",@"LAmade"],
@[@"cn.fmnii.com",@"LAMARQUE"],
@[@"cn.fmnii.com",@"Lanston"],
@[@"cn.fmnii.com",@"Lanvin"],
@[@"cn.fmnii.com",@"Laredo"],
@[@"cn.fmnii.com",@"Laundry By Shelli Segal"],
@[@"cn.fmnii.com",@"LAUREN Ralph Lauren"],
@[@"cn.fmnii.com",@"Le Mystere"],
@[@"cn.fmnii.com",@"Le Specs"],
@[@"cn.fmnii.com",@"Leatherock"],
@[@"cn.fmnii.com",@"LeSportsac"],
@[@"cn.fmnii.com",@"Letarte"],
@[@"cn.fmnii.com",@"Level 99"],
@[@"cn.fmnii.com",@"Levi's?"],
@[@"cn.fmnii.com",@"LFL By Lust For Life"],
@[@"cn.fmnii.com",@"Liebeskind"],
@[@"cn.fmnii.com",@"Life Is Beautiful"],
@[@"cn.fmnii.com",@"Life Is Good"],
@[@"cn.fmnii.com",@"Lifefactory"],
@[@"cn.fmnii.com",@"LifeStride"],
@[@"cn.fmnii.com",@"Lilla P"],
@[@"cn.fmnii.com",@"Lilly Pulitzer"],
@[@"cn.fmnii.com",@"Limi Feu"],
@[@"cn.fmnii.com",@"Linda Farrow Luxe"],
@[@"cn.fmnii.com",@"Linksoul"],
@[@"cn.fmnii.com",@"Lipault Paris"],
@[@"cn.fmnii.com",@"Lisette L Montreal"],
@[@"cn.fmnii.com",@"Little Giraffe"],
@[@"cn.fmnii.com",@"Liverpool"],
@[@"cn.fmnii.com",@"Livie & Luca"],
@[@"cn.fmnii.com",@"LNA"],
@[@"cn.fmnii.com",@"Lodis Accessories"],
@[@"cn.fmnii.com",@"Loeffler Randall"],
@[@"cn.fmnii.com",@"Lole"],
@[@"cn.fmnii.com",@"Lolli LIVING"],
@[@"cn.fmnii.com",@"Lorna Jane"],
@[@"cn.fmnii.com",@"Lotus"],
@[@"cn.fmnii.com",@"Louis Garneau"],
@[@"cn.fmnii.com",@"Louise Et Cie"],
@[@"cn.fmnii.com",@"LOVE Moschino"],
@[@"cn.fmnii.com",@"Love Quotes"],
@[@"cn.fmnii.com",@"Lovers + Friends"],
@[@"cn.fmnii.com",@"Lowa"],
@[@"cn.fmnii.com",@"Lucchese"],
@[@"cn.fmnii.com",@"Lucky Brand"],
@[@"cn.fmnii.com",@"Lucy Love"],
@[@"cn.fmnii.com",@"Lucy"],
@[@"cn.fmnii.com",@"Luli Fama"],
@[@"cn.fmnii.com",@"Lysse"],
@[@"cn.fmnii.com",@"M"],
@[@"cn.fmnii.com",@"M & F Western"],
@[@"cn.fmnii.com",@"M4D3"],
@[@"cn.fmnii.com",@"Maaji"],
@[@"cn.fmnii.com",@"Maggy London"],
@[@"cn.fmnii.com",@"Magicsuit"],
@[@"cn.fmnii.com",@"Magnanni"],
@[@"cn.fmnii.com",@"Magnum"],
@[@"cn.fmnii.com",@"Majorica"],
@[@"cn.fmnii.com",@"Manduka"],
@[@"cn.fmnii.com",@"Manila Grace"],
@[@"cn.fmnii.com",@"Mara Hoffman"],
@[@"cn.fmnii.com",@"Marc By Marc Jacobs"],
@[@"cn.fmnii.com",@"Marc Fisher LTD"],
@[@"cn.fmnii.com",@"Marc Jacobs"],
@[@"cn.fmnii.com",@"Marc New York By Andrew Marc"],
@[@"cn.fmnii.com",@"Marchesa"],
@[@"cn.fmnii.com",@"Marmot"],
@[@"cn.fmnii.com",@"MARNI"],
@[@"cn.fmnii.com",@"Marsell"],
@[@"cn.fmnii.com",@"Marysia"],
@[@"cn.fmnii.com",@"Massimo Matteo"],
@[@"cn.fmnii.com",@"Matiere"],
@[@"cn.fmnii.com",@"Matisse"],
@[@"cn.fmnii.com",@"Matt Bernson"],
@[@"cn.fmnii.com",@"Maui Jim"],
@[@"cn.fmnii.com",@"Mavi Jeans"],
@[@"cn.fmnii.com",@"MCM"],
@[@"cn.fmnii.com",@"McQ"],
@[@"cn.fmnii.com",@"Me Too"],
@[@"cn.fmnii.com",@"Meli Melo"],
@[@"cn.fmnii.com",@"Members Only"],
@[@"cn.fmnii.com",@"Mephisto"],
@[@"cn.fmnii.com",@"Merrell"],
@[@"cn.fmnii.com",@"Messico"],
@[@"cn.fmnii.com",@"Mezlan"],
@[@"cn.fmnii.com",@"Miansai"],
@[@"cn.fmnii.com",@"Michael Antonio"],
@[@"cn.fmnii.com",@"Michael Bastian Gray Label"],
@[@"cn.fmnii.com",@"Michael Kors"],
@[@"cn.fmnii.com",@"Michael Stars"],
@[@"cn.fmnii.com",@"Michele"],
@[@"cn.fmnii.com",@"MIKOH SWIMWEAR"],
@[@"cn.fmnii.com",@"Mini Melissa"],
@[@"cn.fmnii.com",@"Mini Rodini"],
@[@"cn.fmnii.com",@"Minnetonka"],
@[@"cn.fmnii.com",@"Miraclesuit"],
@[@"cn.fmnii.com",@"Miseno"],
@[@"cn.fmnii.com",@"Missoni"],
@[@"cn.fmnii.com",@"Miu Miu"],
@[@"cn.fmnii.com",@"Miz Mooz"],
@[@"cn.fmnii.com",@"Mizuno"],
@[@"cn.fmnii.com",@"MM6 Maison Margiela"],
@[@"cn.fmnii.com",@"Mod-O-Doc"],
@[@"cn.fmnii.com",@"Monreal London"],
@[@"cn.fmnii.com",@"Montrail"],
@[@"cn.fmnii.com",@"Morgan & Milo Kids"],
@[@"cn.fmnii.com",@"Moschino"],
@[@"cn.fmnii.com",@"Mostly Heard Rarely Seen"],
@[@"cn.fmnii.com",@"Mountain Buggy"],
@[@"cn.fmnii.com",@"Mountain Hardwear"],
@[@"cn.fmnii.com",@"Mountain Khakis"],
@[@"cn.fmnii.com",@"Movado"],
@[@"cn.fmnii.com",@"Mr. Swim"],
@[@"cn.fmnii.com",@"Mud Pie"],
@[@"cn.fmnii.com",@"Munro"],
@[@"cn.fmnii.com",@"Munster Kids"],
@[@"cn.fmnii.com",@"My Flat In London"],
@[@"cn.fmnii.com",@"N"],
@[@"cn.fmnii.com",@"Naked & Famous"],
@[@"cn.fmnii.com",@"Nally & Millie"],
@[@"cn.fmnii.com",@"NANA JUDY"],
@[@"cn.fmnii.com",@"Nanette Lepore"],
@[@"cn.fmnii.com",@"Naot Footwear"],
@[@"cn.fmnii.com",@"Nathan"],
@[@"cn.fmnii.com",@"Native Eyewear"],
@[@"cn.fmnii.com",@"Native Shoes"],
@[@"cn.fmnii.com",@"Natori"],
@[@"cn.fmnii.com",@"Naturalizer"],
@[@"cn.fmnii.com",@"Naturino"],
@[@"cn.fmnii.com",@"NAU"],
@[@"cn.fmnii.com",@"Nautica"],
@[@"cn.fmnii.com",@"Neil Barrett"],
@[@"cn.fmnii.com",@"New Balance"],
@[@"cn.fmnii.com",@"New Era"],
@[@"cn.fmnii.com",@"NewbarK"],
@[@"cn.fmnii.com",@"Newton Running"],
@[@"cn.fmnii.com",@"Next By Athena"],
@[@"cn.fmnii.com",@"NIC+ZOE"],
@[@"cn.fmnii.com",@"Nicole Miller"],
@[@"cn.fmnii.com",@"Nike"],
@[@"cn.fmnii.com",@"Nina"],
@[@"cn.fmnii.com",@"Nine West"],
@[@"cn.fmnii.com",@"Nixon"],
@[@"cn.fmnii.com",@"NO KA'OI"],
@[@"cn.fmnii.com",@"The North Face"],
@[@"cn.fmnii.com",@"Not Rated"],
@[@"cn.fmnii.com",@"Nunn Bush"],
@[@"cn.fmnii.com",@"Nununu"],
@[@"cn.fmnii.com",@"Nurse Mates"],
@[@"cn.fmnii.com",@"NYDJ"],
@[@"cn.fmnii.com",@"O"],
@[@"cn.fmnii.com",@"O'Neill"],
@[@"cn.fmnii.com",@"Oakley"],
@[@"cn.fmnii.com",@"Obermeyer"],
@[@"cn.fmnii.com",@"Obey"],
@[@"cn.fmnii.com",@"Oboz"],
@[@"cn.fmnii.com",@"OGIO"],
@[@"cn.fmnii.com",@"Ohw?"],
@[@"cn.fmnii.com",@"Old Friend"],
@[@"cn.fmnii.com",@"Old Gringo"],
@[@"cn.fmnii.com",@"Old Soles"],
@[@"cn.fmnii.com",@"Old West Boots"],
@[@"cn.fmnii.com",@"Oliberte"],
@[@"cn.fmnii.com",@"Oliver Peoples"],
@[@"cn.fmnii.com",@"OluKai"],
@[@"cn.fmnii.com",@"On"],
@[@"cn.fmnii.com",@"Onex"],
@[@"cn.fmnii.com",@"OnGossamer"],
@[@"cn.fmnii.com",@"Onia"],
@[@"cn.fmnii.com",@"Only Hearts"],
@[@"cn.fmnii.com",@"Onzie"],
@[@"cn.fmnii.com",@"OOFOS"],
@[@"cn.fmnii.com",@"Original Penguin"],
@[@"cn.fmnii.com",@"Orla Kiely"],
@[@"cn.fmnii.com",@"Oscar De La Renta"],
@[@"cn.fmnii.com",@"Osiris"],
@[@"cn.fmnii.com",@"Osprey"],
@[@"cn.fmnii.com",@"OTBT"],
@[@"cn.fmnii.com",@"Outdoor Research"],
@[@"cn.fmnii.com",@"P"],
@[@"cn.fmnii.com",@"P.J. Salvage"],
@[@"cn.fmnii.com",@"Pablosky Kids"],
@[@"cn.fmnii.com",@"Pacsafe"],
@[@"cn.fmnii.com",@"PACT"],
@[@"cn.fmnii.com",@"Paige"],
@[@"cn.fmnii.com",@"Pajar CANADA"],
@[@"cn.fmnii.com",@"Palladium"],
@[@"cn.fmnii.com",@"Pampili"],
@[@"cn.fmnii.com",@"Paradox London Pink"],
@[@"cn.fmnii.com",@"PARC City Boot"],
@[@"cn.fmnii.com",@"Parker Smith"],
@[@"cn.fmnii.com",@"Patricia Green"],
@[@"cn.fmnii.com",@"Patricia Nash"],
@[@"cn.fmnii.com",@"Paul Green"],
@[@"cn.fmnii.com",@"Paul Smith"],
@[@"cn.fmnii.com",@"Pazitos"],
@[@"cn.fmnii.com",@"Pearl Izumi"],
@[@"cn.fmnii.com",@"Pediped"],
@[@"cn.fmnii.com",@"Pedro Garcia"],
@[@"cn.fmnii.com",@"Pelle Moda"],
@[@"cn.fmnii.com",@"Pendleton"],
@[@"cn.fmnii.com",@"Penfield"],
@[@"cn.fmnii.com",@"People Footwear"],
@[@"cn.fmnii.com",@"People's Project LA Kids"],
@[@"cn.fmnii.com",@"Perry Ellis"],
@[@"cn.fmnii.com",@"Persol"],
@[@"cn.fmnii.com",@"Petunia Pickle Bottom"],
@[@"cn.fmnii.com",@"Petzl"],
@[@"cn.fmnii.com",@"PF Flyers"],
@[@"cn.fmnii.com",@"Phil & Teds"],
@[@"cn.fmnii.com",@"Pierre Balmain"],
@[@"cn.fmnii.com",@"Pikolinos"],
@[@"cn.fmnii.com",@"Pistil"],
@[@"cn.fmnii.com",@"PLAE"],
@[@"cn.fmnii.com",@"Plush"],
@[@"cn.fmnii.com",@"Poler"],
@[@"cn.fmnii.com",@"Polo Ralph Lauren"],
@[@"cn.fmnii.com",@"Pomellato 67"],
@[@"cn.fmnii.com",@"Powerstep"],
@[@"cn.fmnii.com",@"Prabal Gurung"],
@[@"cn.fmnii.com",@"Prada"],
@[@"cn.fmnii.com",@"Prana"],
@[@"cn.fmnii.com",@"Preen By Thornton Bregazzi"],
@[@"cn.fmnii.com",@"Pretty Polly"],
@[@"cn.fmnii.com",@"Primigi Kids"],
@[@"cn.fmnii.com",@"Primitive"],
@[@"cn.fmnii.com",@"PRIVATE STOCK"],
@[@"cn.fmnii.com",@"Proenza Schouler"],
@[@"cn.fmnii.com",@"Project Social T"],
@[@"cn.fmnii.com",@"Propet"],
@[@"cn.fmnii.com",@"Publish"],
@[@"cn.fmnii.com",@"PUMA"],
@[@"cn.fmnii.com",@"Pumpkin Patch Kids"],
@[@"cn.fmnii.com",@"Puppies Make Me Happy"],
@[@"cn.fmnii.com",@"Q"],
@[@"cn.fmnii.com",@"QUAY AUSTRALIA"],
@[@"cn.fmnii.com",@"Quiksilver"],
@[@"cn.fmnii.com",@"R"],
@[@"cn.fmnii.com",@"Rachel Comey"],
@[@"cn.fmnii.com",@"Rachel Kids"],
@[@"cn.fmnii.com",@"Rachel Pally"],
@[@"cn.fmnii.com",@"Rachel Zoe"],
@[@"cn.fmnii.com",@"Racine Carrée"],
@[@"cn.fmnii.com",@"RAEN Optics"],
@[@"cn.fmnii.com",@"Rag & Bone"],
@[@"cn.fmnii.com",@"Ralph Lauren Baby"],
@[@"cn.fmnii.com",@"Randolph"],
@[@"cn.fmnii.com",@"Ray-Ban"],
@[@"cn.fmnii.com",@"RAYE"],
@[@"cn.fmnii.com",@"Rebecca Minkoff"],
@[@"cn.fmnii.com",@"Rebecca Taylor"],
@[@"cn.fmnii.com",@"Red Carter"],
@[@"cn.fmnii.com",@"RED VALENTINO"],
@[@"cn.fmnii.com",@"Red Wing Heritage"],
@[@"cn.fmnii.com",@"Reebok"],
@[@"cn.fmnii.com",@"Reef"],
@[@"cn.fmnii.com",@"Religion"],
@[@"cn.fmnii.com",@"Repetto"],
@[@"cn.fmnii.com",@"Report"],
@[@"cn.fmnii.com",@"Richer Poorer"],
@[@"cn.fmnii.com",@"Rieker"],
@[@"cn.fmnii.com",@"Rimowa"],
@[@"cn.fmnii.com",@"Rip Curl"],
@[@"cn.fmnii.com",@"Roark"],
@[@"cn.fmnii.com",@"Robeez"],
@[@"cn.fmnii.com",@"Robert Clergerie"],
@[@"cn.fmnii.com",@"Robert Graham"],
@[@"cn.fmnii.com",@"Robert Lee Morris"],
@[@"cn.fmnii.com",@"Roberto Cavalli"],
@[@"cn.fmnii.com",@"Roberto Coin"],
@[@"cn.fmnii.com",@"Rochas"],
@[@"cn.fmnii.com",@"Rock And Roll Cowboy"],
@[@"cn.fmnii.com",@"Rock And Roll Cowgirl"],
@[@"cn.fmnii.com",@"Rock Your Baby"],
@[@"cn.fmnii.com",@"Rocket Dog"],
@[@"cn.fmnii.com",@"Rockport"],
@[@"cn.fmnii.com",@"Romika"],
@[@"cn.fmnii.com",@"Roper"],
@[@"cn.fmnii.com",@"Roxy"],
@[@"cn.fmnii.com",@"Royal Robbins"],
@[@"cn.fmnii.com",@"Rsvp"],
@[@"cn.fmnii.com",@"Ruffwear"],
@[@"cn.fmnii.com",@"Rupert Sanderson"],
@[@"cn.fmnii.com",@"RVCA"],
@[@"cn.fmnii.com",@"Ryka"],
@[@"cn.fmnii.com",@"S"],
@[@"cn.fmnii.com",@"Saint Laurent"],
@[@"cn.fmnii.com",@"SALEWA"],
@[@"cn.fmnii.com",@"Salomon"],
@[@"cn.fmnii.com",@"Salt Water Sandal By Hoy Shoes"],
@[@"cn.fmnii.com",@"Salvatore Ferragamo"],
@[@"cn.fmnii.com",@"Sam Edelman"],
@[@"cn.fmnii.com",@"Samsonite"],
@[@"cn.fmnii.com",@"San Diego Hat Company"],
@[@"cn.fmnii.com",@"Sanctuary"],
@[@"cn.fmnii.com",@"Sanita"],
@[@"cn.fmnii.com",@"Sanuk"],
@[@"cn.fmnii.com",@"Satorisan"],
@[@"cn.fmnii.com",@"Saucony"],
@[@"cn.fmnii.com",@"Save The Duck"],
@[@"cn.fmnii.com",@"SAXX UNDERWEAR"],
@[@"cn.fmnii.com",@"Sbicca"],
@[@"cn.fmnii.com",@"SCALA"],
@[@"cn.fmnii.com",@"Scarpa"],
@[@"cn.fmnii.com",@"School Issue"],
@[@"cn.fmnii.com",@"Scotch & Soda"],
@[@"cn.fmnii.com",@"Scott Hawaii"],
@[@"cn.fmnii.com",@"Scully"],
@[@"cn.fmnii.com",@"Seafolly"],
@[@"cn.fmnii.com",@"SeaVees"],
@[@"cn.fmnii.com",@"Sebago"],
@[@"cn.fmnii.com",@"See By Chloe"],
@[@"cn.fmnii.com",@"See Kai Run Kids"],
@[@"cn.fmnii.com",@"Seirus"],
@[@"cn.fmnii.com",@"Sergio Rossi"],
@[@"cn.fmnii.com",@"Seychelles"],
@[@"cn.fmnii.com",@"Shellys London"],
@[@"cn.fmnii.com",@"Sherpani"],
@[@"cn.fmnii.com",@"Shimano"],
@[@"cn.fmnii.com",@"Shinola Detroit"],
@[@"cn.fmnii.com",@"Shock Absorber"],
@[@"cn.fmnii.com",@"Show Me Your Mumu"],
@[@"cn.fmnii.com",@"Shwood"],
@[@"cn.fmnii.com",@"Sigerson Morrison"],
@[@"cn.fmnii.com",@"Simple"],
@[@"cn.fmnii.com",@"SJP By Sarah Jessica Parker"],
@[@"cn.fmnii.com",@"Skagen"],
@[@"cn.fmnii.com",@"Skarlett Blue"],
@[@"cn.fmnii.com",@"SKECHERS"],
@[@"cn.fmnii.com",@"Skip Hop"],
@[@"cn.fmnii.com",@"Skirt Sports"],
@[@"cn.fmnii.com",@"Smartwool"],
@[@"cn.fmnii.com",@"Smith Optics"],
@[@"cn.fmnii.com",@"Socksmith"],
@[@"cn.fmnii.com",@"Sof Sole"],
@[@"cn.fmnii.com",@"Sofft"],
@[@"cn.fmnii.com",@"Soft Style"],
@[@"cn.fmnii.com",@"SoftWalk"],
@[@"cn.fmnii.com",@"Sol Sana"],
@[@"cn.fmnii.com",@"SOLE"],
@[@"cn.fmnii.com",@"Solemates"],
@[@"cn.fmnii.com",@"Soleus"],
@[@"cn.fmnii.com",@"SOLO"],
@[@"cn.fmnii.com",@"Soludos"],
@[@"cn.fmnii.com",@"Sonia By Sonia Rykiel"],
@[@"cn.fmnii.com",@"Sonia Rykiel Kids"],
@[@"cn.fmnii.com",@"SOREL"],
@[@"cn.fmnii.com",@"Soybu"],
@[@"cn.fmnii.com",@"Spanx"],
@[@"cn.fmnii.com",@"Speedo"],
@[@"cn.fmnii.com",@"Spenco"],
@[@"cn.fmnii.com",@"Sperry"],
@[@"cn.fmnii.com",@"Spira"],
@[@"cn.fmnii.com",@"Spiritual Gangster"],
@[@"cn.fmnii.com",@"Splendid"],
@[@"cn.fmnii.com",@"Sportmax"],
@[@"cn.fmnii.com",@"Spring Step"],
@[@"cn.fmnii.com",@"Spy Optic"],
@[@"cn.fmnii.com",@"Spyder"],
@[@"cn.fmnii.com",@"Stacy Adams"],
@[@"cn.fmnii.com",@"Stance"],
@[@"cn.fmnii.com",@"Stella McCartney"],
@[@"cn.fmnii.com",@"Stephen Webster"],
@[@"cn.fmnii.com",@"Stetson"],
@[@"cn.fmnii.com",@"Steve Madden"],
@[@"cn.fmnii.com",@"Stonewear Designs"],
@[@"cn.fmnii.com",@"Stonz"],
@[@"cn.fmnii.com",@"Stride Rite"],
@[@"cn.fmnii.com",@"STS Ranchwear"],
@[@"cn.fmnii.com",@"Stuart Weitzman"],
@[@"cn.fmnii.com",@"Suecomma Bonnie"],
@[@"cn.fmnii.com",@"Summit By White Mountain"],
@[@"cn.fmnii.com",@"SunCloud Polarized Optics"],
@[@"cn.fmnii.com",@"Super"],
@[@"cn.fmnii.com",@"Superfeet"],
@[@"cn.fmnii.com",@"Superga"],
@[@"cn.fmnii.com",@"Supra"],
@[@"cn.fmnii.com",@"Susana Monaco"],
@[@"cn.fmnii.com",@"Suunto"],
@[@"cn.fmnii.com",@"Swarovski"],
@[@"cn.fmnii.com",@"Swedish Hasbeens"],
@[@"cn.fmnii.com",@"T"],
@[@"cn.fmnii.com",@"Tabitha Simmons"],
@[@"cn.fmnii.com",@"Tahari By ASL"],
@[@"cn.fmnii.com",@"Tahari"],
@[@"cn.fmnii.com",@"Tamaris"],
@[@"cn.fmnii.com",@"Taos Footwear"],
@[@"cn.fmnii.com",@"Tart"],
@[@"cn.fmnii.com",@"Tasc Performance"],
@[@"cn.fmnii.com",@"Tasha Polizzi"],
@[@"cn.fmnii.com",@"Tavik"],
@[@"cn.fmnii.com",@"Tecnica"],
@[@"cn.fmnii.com",@"Ted Baker"],
@[@"cn.fmnii.com",@"Teeki"],
@[@"cn.fmnii.com",@"Tempur-Pedic"],
@[@"cn.fmnii.com",@"Teva"],
@[@"cn.fmnii.com",@"The FLEXX"],
@[@"cn.fmnii.com",@"The Jetset Diaries"],
@[@"cn.fmnii.com",@"The Kooples"],
@[@"cn.fmnii.com",@"The North Face"],
@[@"cn.fmnii.com",@"The Original Retro Brand"],
@[@"cn.fmnii.com",@"The Sak"],
@[@"cn.fmnii.com",@"The Unbranded Brand"],
@[@"cn.fmnii.com",@"Theory"],
@[@"cn.fmnii.com",@"THERAFIT"],
@[@"cn.fmnii.com",@"Think!"],
@[@"cn.fmnii.com",@"Thirtytwo"],
@[@"cn.fmnii.com",@"Thomas Dean & Co."],
@[@"cn.fmnii.com",@"THOMAS WYLDE"],
@[@"cn.fmnii.com",@"Thorlos"],
@[@"cn.fmnii.com",@"Thorogood"],
@[@"cn.fmnii.com",@"Threads 4 Thought"],
@[@"cn.fmnii.com",@"Three Dots"],
@[@"cn.fmnii.com",@"Tifosi Optics"],
@[@"cn.fmnii.com",@"Timberland"],
@[@"cn.fmnii.com",@"Timbuk2"],
@[@"cn.fmnii.com",@"Timex"],
@[@"cn.fmnii.com",@"TKEES"],
@[@"cn.fmnii.com",@"To Boot New York"],
@[@"cn.fmnii.com",@"Toad & Co"],
@[@"cn.fmnii.com",@"Todd Snyder"],
@[@"cn.fmnii.com",@"Toesox"],
@[@"cn.fmnii.com",@"Toga Pulla"],
@[@"cn.fmnii.com",@"Tolani"],
@[@"cn.fmnii.com",@"Tommy Bahama"],
@[@"cn.fmnii.com",@"Tommy Hilfiger"],
@[@"cn.fmnii.com",@"TOMS"],
@[@"cn.fmnii.com",@"Toni Pons"],
@[@"cn.fmnii.com",@"Toobydoo"],
@[@"cn.fmnii.com",@"Topo Designs"],
@[@"cn.fmnii.com",@"Torino Leather Co."],
@[@"cn.fmnii.com",@"Tory Burch"],
@[@"cn.fmnii.com",@"Touch Ups"],
@[@"cn.fmnii.com",@"Trafalgar"],
@[@"cn.fmnii.com",@"Trask"],
@[@"cn.fmnii.com",@"Travelpro"],
@[@"cn.fmnii.com",@"TravisMathew"],
@[@"cn.fmnii.com",@"Tretorn"],
@[@"cn.fmnii.com",@"Tribal"],
@[@"cn.fmnii.com",@"TriggerPoint"],
@[@"cn.fmnii.com",@"Trimfit"],
@[@"cn.fmnii.com",@"Trina Turk"],
@[@"cn.fmnii.com",@"Trotters"],
@[@"cn.fmnii.com",@"True Grit"],
@[@"cn.fmnii.com",@"True Religion"],
@[@"cn.fmnii.com",@"Tsukihoshi Kids"],
@[@"cn.fmnii.com",@"Tubbs"],
@[@"cn.fmnii.com",@"Tumi"],
@[@"cn.fmnii.com",@"Tundra Boots"],
@[@"cn.fmnii.com",@"TYR"],
@[@"cn.fmnii.com",@"U"],
@[@"cn.fmnii.com",@"UGG"],
@[@"cn.fmnii.com",@"Ultimate Direction"],
@[@"cn.fmnii.com",@"Umi Kids"],
@[@"cn.fmnii.com",@"Under Armour"],
@[@"cn.fmnii.com",@"Union Of Angels"],
@[@"cn.fmnii.com",@"Union"],
@[@"cn.fmnii.com",@"Unique Vintage"],
@[@"cn.fmnii.com",@"United By Blue"],
@[@"cn.fmnii.com",@"Us Angels"],
@[@"cn.fmnii.com",@"V"],
@[@"cn.fmnii.com",@"Valentino"],
@[@"cn.fmnii.com",@"Vaneli"],
@[@"cn.fmnii.com",@"Vanessa Mooney"],
@[@"cn.fmnii.com",@"Vans"],
@[@"cn.fmnii.com",@"Vasque"],
@[@"cn.fmnii.com",@"Vera Bradley"],
@[@"cn.fmnii.com",@"Vera Wang"],
@[@"cn.fmnii.com",@"Veronique Branquihno"],
@[@"cn.fmnii.com",@"Versace"],
@[@"cn.fmnii.com",@"Vestal"],
@[@"cn.fmnii.com",@"Via Spiga"],
@[@"cn.fmnii.com",@"Vibram FiveFingers"],
@[@"cn.fmnii.com",@"Victorinox"],
@[@"cn.fmnii.com",@"Vilebrequin"],
@[@"cn.fmnii.com",@"Vince Camuto"],
@[@"cn.fmnii.com",@"Vince"],
@[@"cn.fmnii.com",@"Vineyard Vines"],
@[@"cn.fmnii.com",@"Vintage 1946"],
@[@"cn.fmnii.com",@"VIONIC"],
@[@"cn.fmnii.com",@"VISSLA"],
@[@"cn.fmnii.com",@"Vitamin A Swimwear"],
@[@"cn.fmnii.com",@"Vivienne Westwood"],
@[@"cn.fmnii.com",@"Vivobarefoot"],
@[@"cn.fmnii.com",@"VOLATILE"],
@[@"cn.fmnii.com",@"Volcom"],
@[@"cn.fmnii.com",@"Volley Australia"],
@[@"cn.fmnii.com",@"VonZipper"],
@[@"cn.fmnii.com",@"W"],
@[@"cn.fmnii.com",@"W6YZ"],
@[@"cn.fmnii.com",@"Wacoal"],
@[@"cn.fmnii.com",@"Walking Cradles"],
@[@"cn.fmnii.com",@"Warm Creature"],
@[@"cn.fmnii.com",@"Stuart Weitzman"],
@[@"cn.fmnii.com",@"Western Chief Kids"],
@[@"cn.fmnii.com",@"Wigwam"],
@[@"cn.fmnii.com",@"Will Leather Goods"],
@[@"cn.fmnii.com",@"Wilson"],
@[@"cn.fmnii.com",@"Wolford"],
@[@"cn.fmnii.com",@"Wolky"],
@[@"cn.fmnii.com",@"Wolverine"],
@[@"cn.fmnii.com",@"Woodlore"],
@[@"cn.fmnii.com",@"Woolrich"],
@[@"cn.fmnii.com",@"Wrightsock"],
@[@"cn.fmnii.com",@"X"],
@[@"cn.fmnii.com",@"XCVI"],
@[@"cn.fmnii.com",@"Y"],
@[@"cn.fmnii.com",@"Y's By Yohji Yamamoto"],
@[@"cn.fmnii.com",@"YakTrax"],
@[@"cn.fmnii.com",@"Yellow Box"],
@[@"cn.fmnii.com",@"YIGAL AZROU?L"],
@[@"cn.fmnii.com",@"Yosi Samra"],
@[@"cn.fmnii.com",@"Young Fabulous & Broke"],
@[@"cn.fmnii.com",@"Yummie By Heather Thomson"],
@[@"cn.fmnii.com",@"Z"],
@[@"cn.fmnii.com",@"1.STATE"],
@[@"cn.fmnii.com",@"2(X)IST"],
@[@"cn.fmnii.com",@"2XU"],
@[@"cn.fmnii.com",@"3.1 Phillip Lim"],
@[@"cn.fmnii.com",@"34 Heritage"],
@[@"cn.fmnii.com",@"4Ward Clothing"],
@[@"cn.fmnii.com",@"5.11 Tactical"],
@[@"cn.fmnii.com",@"6 Shore Road By Pooja"],
@[@"cn.fmnii.com",@"7 Diamonds"],
@[@"cn.fmnii.com",@"7 For All Mankind"]
];}
    return _shoesURLList;
}

- (NSArray*)clueList{
    if (!_clueList) {
        _clueList = @[@"A",@"B",@"C",@"D",@"E",@"F",@"G",@"H",@"I",@"J",@"K",@"L",@"M",@"N",@"O",@"P",@"Q",@"R",@"S",@"T",@"U",@"V",@"W",@"X",@"Y",@"Z"];
    }
    return _clueList;
}
#pragma mark - Table view data source

- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView {
    return 1;
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
    return [self.shoesList count];
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    static NSString *cellIdentifier = @"FMNIIListTVCIdentifier";
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:cellIdentifier];
    cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleValue1 reuseIdentifier:cellIdentifier];
    cell.textLabel.text = self.shoesList[indexPath.row];
    return cell;
}

//右侧索引
//- (NSArray<NSString *> *)sectionIndexTitlesForTableView:(UITableView *)tableView {
//   return self.clueList;
//}

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath{
    Tab *item = [[Tab alloc] init];
    item.type = @"wordpress";
    item.name = self.shoesList[indexPath.row];
    item.params = self.shoesURLList[indexPath.row];
    UIViewController *controller = [FrontNavigationController createViewController:item withStoryboard:self.storyboard];
    
    [self.navigationController pushViewController:controller animated:YES];
}


- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer *)gestureRecognizer
{
    if (self.navigationController.viewControllers.count == 1)
    {
        return NO;
    }
    else
    {
        return YES;
    }
}
    @end
    
